// Generated by CoffeeScript 1.7.1
(function() {
  var spritz;

  this.Spritz = (function() {
    Spritz.prototype.getSelectionText = function() {
      var container, i, selection, text, _i, _ref;
      text = "";
      if (window.getSelection) {
        selection = window.getSelection();
        if (selection.rangeCount) {
          container = document.createElement("div");
          for (i = _i = 0, _ref = selection.rangeCount - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
            container.appendChild(selection.getRangeAt(i).cloneContents());
          }
          text = container.innerText || container.textContent;
        }
      } else if (document.selection) {
        if (document.selection.type === "Text") {
          text = document.selection.createRange().text;
        }
      }
      if (text === "") {
        return false;
      } else {
        return text;
      }
    };

    function Spritz() {
      var wpm, wpmOption, _i;
      this.rootDiv = document.createElement("div");
      this.rootDiv.id = "spritz_root";
      this.rootDiv.align = "center";
      this.resultDiv = document.createElement("div");
      this.resultDiv.id = "spritz_result";
      this.rootDiv.appendChild(this.resultDiv);
      this.formerSpan = document.createElement("span");
      this.formerSpan.id = "spritz_former";
      this.formerSpan.style.fontSize = "32px";
      this.formerSpan.style.fontFamily = "Droid Sans Mono";
      this.resultDiv.appendChild(this.formerSpan);
      this.pivotSpan = document.createElement("span");
      this.pivotSpan.id = "spritz_pivot";
      this.pivotSpan.style.fontSize = "32px";
      this.pivotSpan.style.fontFamily = "Droid Sans Mono";
      this.pivotSpan.style.color = "red";
      this.resultDiv.appendChild(this.pivotSpan);
      this.latterSpan = document.createElement("span");
      this.latterSpan.id = "spritz_latter";
      this.latterSpan.style.fontSize = "32px";
      this.latterSpan.style.fontFamily = "Droid Sans Mono";
      this.resultDiv.appendChild(this.latterSpan);
      this.wpmSelect = document.createElement("select");
      this.wpmSelect.id = "spritz_wpm";
      for (wpm = _i = 200; _i <= 1000; wpm = _i += 50) {
        wpmOption = document.createElement("option");
        wpmOption.text = wpm;
        this.wpmSelect.add(wpmOption);
      }
      this.rootDiv.appendChild(this.wpmSelect);
      this.startButton = document.createElement("button");
      this.startButton.id = "spritz_start";
      this.startButton.onclick = function() {
        return spritz.go();
      };
      this.startButton.innerHTML = "Start";
      this.rootDiv.appendChild(this.startButton);
      this.running = false;
    }

    Spritz.prototype.show = function() {
      if (document.body.firstChild) {
        return document.body.insertBefore(this.rootDiv, document.body.firstChild);
      } else {
        return document.body.appendChild(this.rootDiv);
      }
    };

    Spritz.prototype.hide = function() {
      return document.body.removeChild(this.rootDiv);
    };

    Spritz.prototype.getWPM = function() {
      var selectedIndex, wpm;
      selectedIndex = this.wpmSelect.selectedIndex;
      wpm = this.wpmSelect.options[selectedIndex].text;
      return parseInt(wpm);
    };

    Spritz.prototype.setWord = function(word) {
      var former, latter, pivot, pivotIndex;
      pivotIndex = 0;
      if (word.length > 1) {
        pivotIndex = word.length / 2 - 1;
      }
      pivot = word.charAt(pivotIndex);
      this.pivotSpan.innerHTML = pivot;
      latter = "";
      if (word.length > 1) {
        latter = word.slice(pivotIndex + 1, word.length);
      }
      former = "";
      if (word.length > 2) {
        former = word.slice(0, pivotIndex);
      }
      if (former.length > latter.length) {
        while (former.length > latter.length) {
          latter += "\u00A0";
        }
      } else if (latter.length > former.length) {
        while (latter.length > former.length) {
          former = "\u00A0" + former;
        }
      }
      this.formerSpan.innerHTML = former;
      return this.latterSpan.innerHTML = latter;
    };

    Spritz.prototype.go = function() {
      var callback, currentWordIndex, intervalId, selection, words, wpm;
      selection = this.getSelectionText();
      if (selection.length === 0) {
        alert("Please select text to Spritz");
        return;
      }
      this.running = true;
      words = selection.split(/\s+/);
      currentWordIndex = 0;
      callback = (function(_this) {
        return function() {
          if (currentWordIndex < words.length) {
            return _this.setWord(words[currentWordIndex++]);
          } else {
            clearInterval(intervalId);
            return _this.running = false;
          }
        };
      })(this);
      wpm = this.getWPM();
      return intervalId = setInterval(callback, 60000 / wpm);
    };

    return Spritz;

  })();

  spritz = new Spritz();

  spritz.show();

  spritz.setWord("CoffeeSpritz");

}).call(this);

//# sourceMappingURL=CoffeeSpritz.map
